### ISSUE TITLE
IP object value type

### ISSUE THREAD

**Issue by FR4NK-W** [netsec-ethz/rains#211] opened 2019-01-31 10:23 UTC
The type of the ip object's value is a string. It should be a net.Addr or snet.Addr such that invalid addresses are caught early.

**Comment by chaehni** [comment] 2019-03-08 13:20
duplicate of https://github.com/netsec-ethz/rains/issues/95

**Comment by chaehni** [comment] 2019-04-30 09:13
closed by https://github.com/netsec-ethz/rains/pull/224

**Closed** 2019-04-30 09:13 UTC
